version: '3'
services:
  websocket-server:
    build:
      context: ./server
      dockerfile: Dockerfile.websocket
    ports:
      - "8766:8766"
      - "8767:8767"
    depends_on:
      - redis

  web:
    build:
      context: ./web
    ports:
      - "80:80"
    depends_on:
      - websocket-server

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"