# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8766 and 8767 available to the world outside this container
EXPOSE 8766
EXPOSE 8767

# Run websocket server when the container launches
CMD ["python", "websocket_server.py"]